labels: 
  0 : "noise"
  1 : "animal"
  2: "human_pedestrian_adult"
  3: "human_pedestrian_child"
  4: "human_pedestrian_construction_worker"
  5: "human_pedestrian_personal_mobility"
  6: "human_pedestrian_police_officer"
  7: "human_pedestrian_stroller"
  8: "human_pedestrian_wheelchair"
  9: "movable_object_barrier"
  10: "movable_object_debris"
  11: "movable_object_pushable_pullable"
  12: "movable_object_trafficcone"
  13: "static_object_bicycle_rack"
  14: "vehicle_bicycle"
  15: "vehicle_bus_bendy"
  16: "vehicle_bus_rigid"
  17: "vehicle_car"
  18: "vehicle_construction"
  19: "vehicle_emergency_ambulance"
  20: "vehicle_emergency_police"
  21: "vehicle_motorcycle"
  22: "vehicle_trailer"
  23: "vehicle_truck"
  24: "flat_driveable_surface"
  25: "flat_other"
  26: "flat_sidewalk"
  27: "flat_terrain"
  28: "static_manmade"
  29: "static_other"
  30: "static_vegetation"
  31: "vehicle_ego"