unlabeled: 0.5
outlier: 0.5
car: 0.01
bicycle: 0.01
bus: 0.01
motorcycle: 0.01
on-rails: 0.01
truck: 0.01
other-vehicle: 0.01
person: 0.01
bicyclist: 0.01
motorcyclist: 0.01
road: 0.5
parking: 0.5
sidewalk: 0.5
other-ground: 0.5
building: 0.5
fence: 0.5
other-structure: 1
lane-marking: 0.01
vegetation: 0.5
trunk: 0.5
terrain: 0.5
pole: 0.01
traffic-sign: 0.01
other-object: 0.01
moving-car: 0.01
moving-bicyclist: 0.01
moving-person: 0.01
moving-motorcyclist: 0.01
moving-on-rails: 0.01
moving-bus: 0.01
moving-truck: 0.01
moving-other-vehicle: 0.01
