noise: 0.5
animal: 0.01
human_pedestrian_adult: 0.01
human_pedestrian_child: 0.01
human_pedestrian_construction_worker: 0.01
human_pedestrian_personal_mobility: 0.01
human_pedestrian_police_officer: 0.01
human_pedestrian_stroller: 0.01
human_pedestrian_wheelchair: 0.01
movable_object_barrier: 0.01
movable_object_debris: 0.01
movable_object_pushable_pullable: 0.01
movable_object_trafficcone: 0.01
static_object_bicycle_rack: 0.01
vehicle_bicycle: 0.01
vehicle_bus_bendy: 0.01
vehicle_bus_rigid: 0.01
vehicle_car: 0.01
vehicle_construction: 0.01
vehicle_emergency_ambulance: 0.01
vehicle_emergency_police: 0.01
vehicle_motorcycle: 0.01
vehicle_trailer: 0.01
vehicle_truck: 0.01
flat_driveable_surface: 0.5
flat_other: 0.5
flat_sidewalk: 0.25
flat_terrain: 0.5
static_manmade: 0.25
static_other: 0.5
static_vegetation: 0.5
vehicle_ego: 0.5